kind: pipeline
type: docker
name: materials-pipeline

steps:
  # 构建并推送后端 Docker 镜像
  - name: build-and-push-backend-image
    image: plugins/docker
    settings:
      # 私有仓库的地址
      registry: 192.168.3.5:6000
      # 镜像仓库和名称
      repo: 192.168.3.5:6000/materials-backend
      # 使用 Git 提交哈希作为标签，保证唯一性
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
        - latest
      # Dockerfile 的路径
      dockerfile: backend/Dockerfile
      # 构建上下文
      context: backend
      # 如果您的私有仓库没有配置 SSL (即使用 http)，则需要此项
      insecure: true

  # 构建并推送前端 Docker 镜像
  - name: build-and-push-frontend-image
    image: plugins/docker
    settings:
      # 私有仓库的地址
      registry: 192.168.3.5:6000
      # 镜像仓库和名称
      repo: 192.168.3.5:6000/materials-frontend
      # 使用 Git 提交哈希作为标签，保证唯一性
      tags:
        - ${DRONE_COMMIT_SHA:0:7}
        - latest
      # Dockerfile 的路径
      dockerfile: Dockerfile
      # 构建上下文
      context: .
      # 如果您的私有仓库没有配置 SSL (即使用 http)，则需要此项
      insecure: true

  # 在本机直接部署后端
  - name: deploy-backend-on-host
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Deploying backend on the host machine..."
      # 拉取最新的 Docker 镜像
      - docker pull 192.168.3.5:6000/materials-backend:latest
      # 停止并删除旧的容器 (如果存在)
      - docker stop materials-backend-container || true
      - docker rm materials-backend-container || true
      # 启动新容器
      - docker run -d --name materials-backend-container -p 8000:8000 --restart always 192.168.3.5:6000/materials-backend:latest

  # 在本机直接部署前端
  - name: deploy-frontend-on-host
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Deploying frontend on the host machine..."
      # 拉取最新的 Docker 镜像
      - docker pull 192.168.3.5:6000/materials-frontend:latest
      # 停止并删除旧的容器 (如果存在)
      - docker stop materials-frontend-container || true
      - docker rm materials-frontend-container || true
      # 启动新容器 (使用 8080 端口避免冲突)
      - docker run -d --name materials-frontend-container -p 8089:80 --restart always 192.168.3.5:6000/materials-frontend:latest

trigger:
  branch:
    - main
    - develop
    - feature/*
    - release/*
  event:
    - push
    - tag
    - deployment
    - pull_request
    - custom

# 定义一个数据卷，用于挂载 Docker Socket
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
