kind: pipeline
type: docker
name: materials-pipeline

steps:
  - name: build-frontend
    image: node:18-alpine
    commands:
      - npm install
      - npm run build
    volumes:
      - name: cache
        path: /app/node_modules

  - name: build-backend
    image: python:3.11-slim
    commands:
      - pip install -r backend/requirements.txt
    volumes:
      - name: cache
        path: /root/.cache

  - name: run-docker-compose
    image: docker:latest
    commands:
      - sleep 20  # 增加等待时间以确保 Docker 守护进程完全启动
      - docker info  # 检查 Docker 守护进程状态
      - ls -la  # 检查当前目录内容
      - pwd  # 显示当前工作目录
      - docker-compose up -d --build  # 使用 --build 确保构建最新镜像
    volumes:
      - name: dockersock
        path: /var/run
      - name: drone-src
        path: /drone/src
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock

trigger:
  branch:
    - main
    - develop
    - feature/*
    - release/*
  event:
    - push
    - tag
    - deployment
    - pull_request
    - custom

services:
  - name: docker
    image: docker:dind
    privileged: true
    command: ["dockerd", "--host", "unix:///var/run/docker.sock"]
    volumes:
      - name: dockersock
        path: /var/run
      - name: drone-src
        path: /drone/src

volumes:
  - name: dockersock
    temp: {}
  - name: cache
    temp: {}
  - name: drone-src
    temp: {}
