version: '3.8'

services:
  backend:
    build: ./backend
    container_name: materials-backend
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      - ./data:/app/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: materials-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 