version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: materials-backend
    restart: always
    environment:
      - ENV=production
      - SECRET_KEY=your_secret_key_here
      - CORS_ORIGINS=["*"]
      - DB_HOST=192.168.3.5
      - DB_PORT=3306
      - DB_NAME=Sap
      - DB_USER=root
      - DB_PASSWORD=19931225Yfl
    ports:
      - "8000:8000"
    volumes:
      - ./backend/materials.db:/app/materials.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: materials-frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=http://materials-backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: materials_network
    driver: bridge